// flow-typed signature: 5805d6823e1a1ddddfcaa0cbe78e201d
// flow-typed version: <<STUB>>/prettier_v^1.4.4/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prettier-space-parenthesis'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'prettier-space-parenthesis' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'prettier-space-parenthesis/bin/prettier' {
  declare module.exports: any;
}

declare module 'prettier-space-parenthesis/parser-babylon' {
  declare module.exports: any;
}

declare module 'prettier-space-parenthesis/parser-flow' {
  declare module.exports: any;
}

declare module 'prettier-space-parenthesis/parser-graphql' {
  declare module.exports: any;
}

declare module 'prettier-space-parenthesis/parser-postcss' {
  declare module.exports: any;
}

declare module 'prettier-space-parenthesis/parser-typescript' {
  declare module.exports: any;
}

// Filename aliases
declare module 'prettier-space-parenthesis/bin/prettier.js' {
  declare module.exports: $Exports<'prettier-space-parenthesis/bin/prettier'>;
}
declare module 'prettier-space-parenthesis/index' {
  declare module.exports: $Exports<'prettier-space-parenthesis'>;
}
declare module 'prettier-space-parenthesis/index.js' {
  declare module.exports: $Exports<'prettier-space-parenthesis'>;
}
declare module 'prettier-space-parenthesis/parser-babylon.js' {
  declare module.exports: $Exports<'prettier-space-parenthesis/parser-babylon'>;
}
declare module 'prettier-space-parenthesis/parser-flow.js' {
  declare module.exports: $Exports<'prettier-space-parenthesis/parser-flow'>;
}
declare module 'prettier-space-parenthesis/parser-graphql.js' {
  declare module.exports: $Exports<'prettier-space-parenthesis/parser-graphql'>;
}
declare module 'prettier-space-parenthesis/parser-postcss.js' {
  declare module.exports: $Exports<'prettier-space-parenthesis/parser-postcss'>;
}
declare module 'prettier-space-parenthesis/parser-typescript.js' {
  declare module.exports: $Exports<'prettier-space-parenthesis/parser-typescript'>;
}
